- hosts: servers
  become: true
  tasks:

  - name: #Установка программ для оптимизации системы
    ansible.builtin.package:
      name:
        - grc
        - htop
        - tree
        - mc
      state: latest
      